-- src/shared/Movement/MovementStates/MovementStateDefs.luau
return {
	Idle = "Idle",
	Walking = "Walking",
	Running = "Running",
	Crouching = "Crouching",
	CrouchWalking = "CrouchWalking",
	Dashing = "Dashing",
	Sliding = "Sliding",
	Jumping = "Jumping",
	Falling = "Falling",
	
	-- ADVANCED QINGGONG STATES
	WallHanging = "WallHanging",
	WallBoost = "WallBoost", 
	WallRunning = "WallRunning",
	LedgeVaulting = "LedgeVaulting",
	WallLeaping = "WallLeaping",
}