return {
	Idle = "Idle",
	Walking = "Walking",
	Running = "Running",
	Sprinting = "Sprinting",
	Crouching = "Crouching",
	CrouchWalking = "CrouchWalking",
	Dashing = "Dashing",
	Sliding = "Sliding",
	Jumping = "Jumping",
	DoubleJumping = "DoubleJumping",
	WallClingDoubleJump = "WallClingDoubleJump", -- small recovery hop off a WallBoost, strictly for reconnecting to a wall
	Falling = "Falling",
	AirDashing = "AirDashing",

	-- ADVANCED QINGGONG STATES
	WallHanging = "WallHanging",
	WallBoost = "WallBoost",
	WallRunning = "WallRunning",
	WallLeaping = "WallLeaping",
	LedgeJumping = "LedgeJumping",
	LightLanding = "LightLanding",
	HeavyLanding = "HeavyLanding",
}